//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.15 at 02:27:51 PM IST 
//


package xmlParser;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlParser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlParser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttachmentSet }
     * 
     */
    public AttachmentSet createAttachmentSet() {
        return new AttachmentSet();
    }

    /**
     * Create an instance of {@link DescribeVolumesResponse }
     * 
     */
    public DescribeVolumesResponse createDescribeVolumesResponse() {
        return new DescribeVolumesResponse();
    }

    /**
     * Create an instance of {@link DescribeSnapshotsResponse }
     * 
     */
    public DescribeSnapshotsResponse createDescribeSnapshotsResponse() {
        return new DescribeSnapshotsResponse();
    }

    /**
     * Create an instance of {@link DescribeSnapshotsResponse.SnapshotSet }
     * 
     */
    public DescribeSnapshotsResponse.SnapshotSet createDescribeSnapshotsResponseSnapshotSet() {
        return new DescribeSnapshotsResponse.SnapshotSet();
    }

    /**
     * Create an instance of {@link DescribeVolumesResponse.VolumeSet }
     * 
     */
    public DescribeVolumesResponse.VolumeSet createDescribeVolumesResponseVolumeSet() {
        return new DescribeVolumesResponse.VolumeSet();
    }

    /**
     * Create an instance of {@link AttachmentSet.AttachmentEO }
     * 
     */
    public AttachmentSet.AttachmentEO createAttachmentSetAttachmentEO() {
        return new AttachmentSet.AttachmentEO();
    }

    /**
     * Create an instance of {@link CreateSnapshotResponse }
     * 
     */
    public CreateSnapshotResponse createCreateSnapshotResponse() {
        return new CreateSnapshotResponse();
    }

    /**
     * Create an instance of {@link DeleteVolumeResponse }
     * 
     */
    public DeleteVolumeResponse createDeleteVolumeResponse() {
        return new DeleteVolumeResponse();
    }

    /**
     * Create an instance of {@link CreateVolumeResponse }
     * 
     */
    public CreateVolumeResponse createCreateVolumeResponse() {
        return new CreateVolumeResponse();
    }

    /**
     * Create an instance of {@link DeleteSnapshotResponse }
     * 
     */
    public DeleteSnapshotResponse createDeleteSnapshotResponse() {
        return new DeleteSnapshotResponse();
    }

    /**
     * Create an instance of {@link DescribeSnapshotsResponse.SnapshotSet.Item }
     * 
     */
    public DescribeSnapshotsResponse.SnapshotSet.Item createDescribeSnapshotsResponseSnapshotSetItem() {
        return new DescribeSnapshotsResponse.SnapshotSet.Item();
    }

    /**
     * Create an instance of {@link DescribeVolumesResponse.VolumeSet.Item }
     * 
     */
    public DescribeVolumesResponse.VolumeSet.Item createDescribeVolumesResponseVolumeSetItem() {
        return new DescribeVolumesResponse.VolumeSet.Item();
    }

}
