package com.jcs.sbs.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import com.google.gson.Gson;

/**
 * Result class for describe volumes operation.
 */
public class DescribeVolumesResult extends JCSResult implements Serializable, Cloneable {

    private static final long serialVersionUID = -3376670842859374348L;

    private List<Volume> volumes = new ArrayList<Volume>();

    /**
     * Default constructor for CreateSnapshotRequest object.
     */
    public DescribeVolumesResult() {
    }

    /**
     * Returns list of volume objects corresponding to the describe volumes API
     * response.
     * 
     * @return The list of Volume objects, which is generated by unmarshalling
     *         the response xml returned by describe volumes API.
     */
    public List<Volume> getVolumes() {
        return volumes;
    }

    /**
     * Used internally to set the collection of volumes, passed as an argument
     * in DescribeVolumesResult object.
     * 
     * @param volumes
     *            Collection of volume objects which is to be set in
     *            DescribeVolumesResult object.
     */
    public void setVolumes(Collection<Volume> volumes) {
        if (volumes == null) {
            this.volumes = new ArrayList<Volume>();
            return;
        }

        this.volumes = new ArrayList<Volume>(volumes);
    }

    /**
     * Sets the Volume objects, passed as varargs, in the DescribeVolumesResult
     * object and returns the modified DescribeVolumesResult object
     * 
     * @param volumes
     *            List of Volume objects as varargs (variable number of
     *            arguments)
     * @return Modified DescribeVolumesResult object
     */
    public DescribeVolumesResult withVolumes(Volume... volumes) {
        if (this.volumes == null) {
            setVolumes(new ArrayList<Volume>(volumes.length));
        }
        for (Volume ele : volumes) {
            this.volumes.add(ele);
        }
        return this;
    }

    /**
     * Sets the Volume objects, passed as collection of Volume objects, in the
     * DescribeVolumesResult object and returns the modified
     * DescribeVolumesResult object
     * 
     * @param volumes
     *            Collection of Volume objects
     * @return Modified DescribeVolumesResult object
     */
    public DescribeVolumesResult withVolumes(Collection<Volume> volumes) {
        setVolumes(volumes);
        return this;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((volumes == null) ? 0 : volumes.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!super.equals(obj))
            return false;
        if (getClass() != obj.getClass())
            return false;
        DescribeVolumesResult other = (DescribeVolumesResult) obj;
        if (volumes == null) {
            if (other.volumes != null)
                return false;
        } else if (!volumes.equals(other.volumes))
            return false;
        return true;
    }

    /**
     * Creates and returns a copy of this object.
     * 
     * @see java.lang.Object#clone()
     */
    @Override
    public DescribeVolumesResult clone() {
        try {
            return (DescribeVolumesResult) super.clone();
        } catch (CloneNotSupportedException e) {
            throw new IllegalStateException(
                    "Got a CloneNotSupportedException from Object.clone() even though we're Cloneable!", e);
        }
    }
}