package com.jcs.sbs.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class DescribeVolumesResult extends JCSResult implements Serializable, Cloneable {

    private static final long serialVersionUID = -3376670842859374348L;

    private List<Volume> volumes = new ArrayList<Volume>();

    private String nextToken;

    /**
     * Default constructor for CreateSnapshotRequest object.
     */
    public DescribeVolumesResult() {
    }

    /**
     * Returns list of volume objects corresponding to the response returned by
     * describe volumes API.
     * 
     * @return The list of Volume objects, which is generated by unmarshalling
     *         the response xml returned by describe volumes API.
     */
    public List<Volume> getVolumes() {
        return volumes;
    }

    /**
     * Used internally. It sets the collection of volumes, passed
     * as an argument in DescribeVolumesResult object.
     * 
     * @param volumes
     *            Collection of volume objects which is to be set in
     *            DescribeVolumesResult object.
     */
    public void setVolumes(Collection<Volume> volumes) {
        if (volumes == null) {
            this.volumes = new ArrayList<Volume>();
            return;
        }

        this.volumes = new ArrayList<Volume>(volumes);
    }

    /**
     * Sets the Volume objects, passed as varargs, in the
     * DescribeVolumesResult object and returns the modified
     * DescribeVolumesResult object
     * 
     * @param volumes
     *            List of Volume objects as varargs (variable number of
     *            arguments)
     * @return Modified DescribeVolumesResult object
     */
    public DescribeVolumesResult withVolumes(Volume... volumes) {
        if (this.volumes == null) {
            setVolumes(new ArrayList<Volume>(volumes.length));
        }
        for (Volume ele : volumes) {
            this.volumes.add(ele);
        }
        return this;
    }

    /**
     * Sets the Volume objects, passed as collection of Volume
     * objects, in the DescribeVolumesResult object and returns the modified
     * DescribeVolumesResult object
     * 
     * @param volumes
     *            Collection of Volume objects
     * @return Modified DescribeVolumesResult object
     */
    public DescribeVolumesResult withVolumes(Collection<Volume> volumes) {
        setVolumes(volumes);
        return this;
    }

    /**
     * If the describeVolumes() method was called with a MaxResults option, all
     * items would not have been returned. To get next set of items in
     * subsequent call, the ID of the last seen item is returned as 'nextToken'.
     * Next time when the describeVolumes() method is called, this 'nextToken'
     * should be passed to get the next set of items.
     * 
     * This method sets the next token in DescribeVolumesResult object.
     * 
     * @param nextToken
     *            The 'nextToken' value that is returned by the describe volumes
     *            API. This is basically the ID of the last seen item in
     *            response of describeVolumes()
     */
    public void setNextToken(String nextToken) {
        this.nextToken = nextToken;
    }

    /**
     * Returns nextToken value which is used to get next set of items in subsequent calls of describeVolumes() method.
     * 
     * @return The ID of the last seen item (nextToken) in response of
     *         describeVolumes()
     */
    public String getNextToken() {
        return this.nextToken;
    }

    /**
     * If the describeVolumes() method was called with a MaxResults option, all
     * items would not have been returned. To get next set of items in
     * subsequent call, the ID of the last seen item is returned as 'nextToken'.
     * Next time when the describeVolumes() method is called, this 'nextToken'
     * should be passed to get the next set of items.
     * 
     * This method sets the next token in DescribeVolumesResult object and
     * returns the modified DescribeVolumesResult object.
     * 
     * @param nextToken
     *            The ID of the last seen item in response of describeVolumes()
     * @return Modified DescribeVolumesResult object.
     */
    public DescribeVolumesResult withNextToken(String nextToken) {
        setNextToken(nextToken);
        return this;
    }

    @Override
    public String toString() {
        return this.getXml();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;

        if (obj instanceof DescribeVolumesResult == false)
            return false;
        DescribeVolumesResult other = (DescribeVolumesResult) obj;
        if (other.getVolumes() == null ^ this.getVolumes() == null)
            return false;
        if (other.getVolumes() != null && other.getVolumes().equals(this.getVolumes()) == false)
            return false;
        if (other.getNextToken() == null ^ this.getNextToken() == null)
            return false;
        if (other.getNextToken() != null && other.getNextToken().equals(this.getNextToken()) == false)
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode + ((getVolumes() == null) ? 0 : getVolumes().hashCode());
        hashCode = prime * hashCode + ((getNextToken() == null) ? 0 : getNextToken().hashCode());
        return hashCode;
    }

    @Override
    public DescribeVolumesResult clone() {
        try {
            return (DescribeVolumesResult) super.clone();
        } catch (CloneNotSupportedException e) {
            throw new IllegalStateException(
                    "Got a CloneNotSupportedException from Object.clone() " + "even though we're Cloneable!", e);
        }
    }
}